name 'gce_mysql_proxy'
maintainer 'Kristian Van Der Vliet'
maintainer_email 'vanders@liqwyd.com'
license 'Apache v2.0'
source_url 'https://github.com/Liqwyd/gce_mysql_proxy'
description 'Installs & configure a GCE MySQL proxy'
long_description 'Installs and configures the Google Compute Engine MySQL proxy'
version '0.1.1'

depends 'runit', '~> 1.7.6'
